apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: APP_WEB_URL
            - name: CELERY_BROKER_URL
              value: redis://:difyai123456@redis:6379/1
            - name: CONSOLE_API_URL
            - name: CONSOLE_CORS_ALLOW_ORIGINS
              value: '*'
            - name: CONSOLE_WEB_URL
            - name: DB_DATABASE
              value: dify
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              value: difyai123456
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: FILES_URL
            - name: LOG_LEVEL
              value: INFO
            - name: MAIL_DEFAULT_SEND_FROM
              value: 'YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)'
            - name: MAIL_TYPE
            - name: MIGRATION_ENABLED
              value: "true"
            - name: MILVUS_HOST
              value: 127.0.0.1
            - name: MILVUS_PASSWORD
              value: Milvus
            - name: MILVUS_PORT
              value: "19530"
            - name: MILVUS_SECURE
              value: "false"
            - name: MILVUS_USER
              value: root
            - name: MODE
              value: api
            - name: QDRANT_API_KEY
              value: difyai123456
            - name: QDRANT_CLIENT_TIMEOUT
              value: "20"
            - name: QDRANT_URL
              value: http://qdrant:6333
            - name: REDIS_DB
              value: "0"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: difyai123456
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USERNAME
            - name: REDIS_USE_SSL
              value: "false"
            - name: RESEND_API_KEY
            - name: RESEND_API_URL
              value: https://api.resend.com
            - name: S3_ACCESS_KEY
              value: ak-difyai
            - name: S3_BUCKET_NAME
              value: difyai
            - name: S3_ENDPOINT
              value: https://xxx.r2.cloudflarestorage.com
            - name: S3_REGION
              value: us-east-1
            - name: S3_SECRET_KEY
              value: sk-difyai
            - name: SECRET_KEY
              value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
            - name: SENTRY_DSN
            - name: SENTRY_PROFILES_SAMPLE_RATE
              value: "1"
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: "1"
            - name: SERVICE_API_URL
            - name: STORAGE_LOCAL_PATH
              value: storage
            - name: STORAGE_TYPE
              value: local
            - name: VECTOR_STORE
              value: weaviate
            - name: WEAVIATE_API_KEY
              value: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            - name: WEAVIATE_ENDPOINT
              value: http://weaviate:8080
            - name: WEB_API_CORS_ALLOW_ORIGINS
              value: '*'
          image: langgenius/dify-api:0.5.1
          name: api
          resources: {}
          volumeMounts:
            - mountPath: /app/api/storage
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
