apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: weaviate
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weaviate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: weaviate
    spec:
      containers:
        - env:
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "false"
            - name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
              value: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
            - name: AUTHENTICATION_APIKEY_ENABLED
              value: "true"
            - name: AUTHENTICATION_APIKEY_USERS
              value: hello@dify.ai
            - name: AUTHORIZATION_ADMINLIST_ENABLED
              value: "true"
            - name: AUTHORIZATION_ADMINLIST_USERS
              value: hello@dify.ai
            - name: CLUSTER_HOSTNAME
              value: node1
            - name: DEFAULT_VECTORIZER_MODULE
              value: none
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
          image: semitechnologies/weaviate:1.19.0
          name: weaviate
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/weaviate
              name: weaviate-claim0
      restartPolicy: Always
      volumes:
        - name: weaviate-claim0
          persistentVolumeClaim:
            claimName: weaviate-claim0
status: {}
